Add pie and line chart tabs to query result preview
groveco/django-sql-explorer pull request #481
Opened 2022-07-27 23:46 UTC by eeriksp

2022-07-28 07:26 UTC, marksweb requested changes

2022-07-28 07:26 UTC, marksweb commented on explorer/views/utils.py
> +from explorer.chart import get_pie_chart, get_line_chart
Lets rename the module as it already has 2 types of chart;

```suggestion
from explorer.charts import get_pie_chart, get_line_chart
```

2022-08-02 07:43 UTC, eeriksp commented
@marksweb, thank you for amendments, they have all been incorporated now.
Anything else you would like to change?

2022-08-03 00:34 UTC, marksweb requested changes

2022-08-03 00:34 UTC, marksweb commented on docs/features.rst
> +To enable this feature, set `` `` setting to ``True`` and install the plotting libraries ``matplotlib`` and ``seaborn`` with
Looks like this needs the actual setting name.

```suggestion
To enable this feature, set ``EXPLORER_CHARTS_ENABLED`` setting to ``True`` and install the plotting libraries ``matplotlib`` and ``seaborn`` with
```

2022-08-18 10:28 UTC, marksweb commented
@eeriksp Just realised, this needs the `setup.py` updating to handle the optional dependencies added here.

There's a good example here; https://github.com/anymail/django-anymail/blob/main/setup.py#L62

At the moment we've got;

```
extras_require={
        "xls": [
            'xlsxwriter>=1.2.1'
        ]
    },
```

So this could go in with the feature name;

```
extras_require={
        "graphs": [
            'matplotlib<4',
            'seaborn<0.12'
        ]
        "xls": [
            'xlsxwriter>=1.2.1'
        ]
    },
```

2022-08-31 23:09 UTC, merged